### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Ring has ~dupe adjacent pts', geom/src/ring.rs:42:24

### ISSUE THREAD

**Issue by strct** [a-b-street/abstreet#514] opened 2021-02-14 16:07 UTC
I don't know what caused the crash. I was just clicking around. I was following a cyclist, who rode outside the city.

```gdb
Alert at 09:33:00.0 (Person(PersonID(8133))): Person 8133 had a trip cancelled, and their car was warped to Onstreet(LaneID(1641), 3)
Alert at 09:35:00.0 (Person(PersonID(6980))): Person 6980 had a trip cancelled, and their car was warped to Onstreet(LaneID(1894), 3)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Ring has ~dupe adjacent pts', geom/src/ring.rs:42:24
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
   3: geom::ring::Ring::must_new
   4: map_gui::render::car::DrawCar::new
   5: map_gui::render::draw_vehicle
   6: map_gui::render::agents::AgentCache::populate_if_needed
   7: game::app::App::get_renderables_back_to_front
   8: game::app::App::draw
   9: widgetry::app_state::App<A>::draw
  10: widgetry::runner::State<A>::draw
  11: widgetry::runner::run::{{closure}}
  12: winit::platform_impl::platform::x11::EventLoop<T>::run
  13: winit::platform_impl::platform::EventLoop<T>::run
  14: winit::event_loop::EventLoop<T>::run
  15: widgetry::runner::run
  16: game::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

********************************************************************************
Wrote ../data/player/camera_state/seattle/montlake.json
Crash! Please report to https://github.com/a-b-street/abstreet/issues/ and include all output.txt; at least everything starting from the stack trace above!

At 09:35:13.5

Camera:
{ "cam_x": 5377.687570000133, "cam_y": 253.67873000000395, "cam_zoom": 4.840000000000101 }

No edits

Crash! Please report to https://github.com/a-b-street/abstreet/issues/ and include all output.txt; at least everything above here until the start of the report!
********************************************************************************
```

OS: Debian 10
Version: [v0.2.30](https://github.com/a-b-street/abstreet/releases/tag/v0.2.30)

**Comment by dabreegster** [comment] 2021-02-14 22:14
Thanks for reporting! I can't reproduce this, but there are lots of weird cases with rendering vehicles when the roads have sharp angles. If this happens again, instead of crashing, it'll just fallback to a less car-like shape temporarily.

I'm building this week's release now with this fix; I'll close the bug when it's out.

**Comment by dabreegster** [comment] 2021-02-14 23:35
Fixed in https://github.com/a-b-street/abstreet/releases/tag/v0.2.31. Enjoy!

**Closed by dabreegster** 2021-02-14 23:35 UTC
