### ISSUE TITLE
The app chrashed while doing the tutorial

### ISSUE THREAD

**Issue by aFrogThatExists** [a-b-street/abstreet#1070] opened 2023-03-03 11:11 UTC
I was speeding up time while following the car and a popup message saying the app chrashed popped up
<img width="950" alt="Skärmbild 2023-03-03 120848" src="https://user-images.githubusercontent.com/54812998/222705766-6575af34-340d-433f-8de6-a0bf34d84657.png">

**Comment by aFrogThatExists** [comment] 2023-03-03 11:12
"från" means "from" in swedish*

**Comment by dabreegster** [comment] 2023-04-10 09:34
Duplicate of #1078

**Closed by dabreegster** 2023-04-10 09:34 UTC
