### ISSUE TITLE
Crash when clicking on a parking lot

### ISSUE THREAD

**Issue by Antonin-duda** [a-b-street/abstreet#1118] opened 2023-09-18 13:57 UTC
panicked at 'already mutably borrowed: BorrowError', /home/dabreegster/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.0/src/platform_impl/web/event_loop/runner.rs:509:30

**Comment by dabreegster** [comment] 2023-09-18 14:07
Thanks for reporting! Could you help us reproduce this -- what map, did you start a traffic sim in any special way, etc?

**Comment by Antonin-duda** [comment] 2023-09-20 10:30
https://github.com/a-b-street/abstreet/assets/87385742/8fb8f359-bbd0-438d-910c-f8e96164df02

**Comment by dabreegster** [comment] 2023-09-29 16:46
Thanks for reporting! The problem was "prebaked" simulation data covering this map and scenario without any edits. It had gone out of date; I've been bad about regenerating this lately, because the simulation on this map crashes. (#996) I've removed the prebaked data, so this crash will be fixed in the next release, though the traffic simulation will still crash elsewhere.

**Closed by dabreegster** 2023-09-29 16:46 UTC
